name: image_recognition_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    # Riverpod
  flutter_hooks:
  hooks_riverpod:
  # Firebase

  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  firebase_core: 
  firebase_storage:
  firebase_database:
  cloud_firestore:
  google_ml_kit:
  flutter_svg:
  file_picker:
  photo_view:
  google_mlkit_face_detection: ^0.8.0
  http:
  camera:
  photo_manager:
  share_plus:
  tflite_flutter: 
  tflite_flutter_helper: 
  shared_preferences:
  google_mlkit_image_labeling: ^0.9.0
  image:


dev_dependencies:
  flutter_test: 
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
